name: Code Spell Checker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  check-code-spell:
    name: Check Spelling
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup pnpm and install Node.js dependencies
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.x
          run_install: true

      - name: Run cspell
        id: cspell
        run: pnpm spell-checker
        continue-on-error: true

      - name: Extract and Count Errors
        run: |
          cspell_output="${{ steps.cspell.outputs.stdout }}"
          echo "Test: $cspell_output"
          issues_found=$(echo "$cspell_output" | awk -F'Issues found: ' '{print $2}' | cut -d' ' -f1)
          echo "Issues found: $issues_found"
          if [ -n "$issues_found" ] && [ "$issues_found" -gt 2 ]; then
            echo "::error CSpell errors exceed the limit. Failing the action."
            echo "::error New cspell errors created. Please check your code"
            exit 1
          fi
