name: Code Spell Checker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  check-code-spell:
    name: Check Spelling
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.x
          run_install: true

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install Node.js dependencies
        run: pnpm i

      - name: Run cspell
        run: pnpm spell-checker
        continue-on-error: true

      - name: Count errors
        run: |
          error_count=$(echo "${{ steps.cspell.outputs.cspell_output }}" | grep -c "Unknown")
          echo "Total errors: $error_count"
          if [ "$error_count" -gt 5 ]; then
            echo "::error CSpell errors exceed the limit. Failing the action"
            echo "::error New cspell errors created. Please check your code"
            exit 1
          fi
